### ISSUE TITLE
Permission error in the Flask chat example

### ISSUE THREAD

**Issue by GiuseppeCofano** [rominirani/genai-apptemplates-googlecloud#4]
I've successfully deployed  the Chat example on Cloud Run with Flask, but I get this error after sending a text to the chat:

` details = "Permission 'aiplatform.endpoints.predict' denied on resource '//aiplatform.googleapis.com/projects/genai-playground-397314/locations/us-central1/publishers/google/models/chat-bison@001' (or it may not exist)."`

I've given the AI Platform Admin role to the Default Compute service account used by the Cloud Run service to make requests against the Vertex AI Chat endpoint.

If I execute the same call as in the app.py manually through a Python3 terminal, the code works like a charm:

```
>>> print(result.text)                                                                                                                                                           
Cloud Run is a serverless compute platform that allows you to run stateless containers that are invocable via HTTP requests.
```

Hence the Vertex AI endpoint is working correctly, I suspect an authentications issue. How is the authentication flow supposed to work? Any suggestion?

**Comment by rominirani** [comment]
Thanks for reporting this. Let's try to get to the root of what might be happening.

I would try the following:
1. The application definitely needs the two environment variables : GCP_REGION and GCP_PROJECT to be set correctly. Ensure that they are set and have the correct values because Vertex AI needs to be initialized with them. I would suggest to look at the deployed Cloud Run service and in the Environment Variables section , just confirm if the values are correct. That would be my first step.

2. The default service account is the one under which this Cloud Run service will run. So ideally, the permissions should be fine in my opinion. Just check that you don't have a different service account that runs your Cloud Run applications because then we will need aiplatform.endpoints.predict permission, etc. Just see if that permission is provided then to the default service account too. 

3. If the problem still exists, I think I might consider adding some log statements. I don't have any logging here in this sample but you will see logging implemented in the Cloud Function samples, just in case you would like to add some statements to see what is happening. 

Do let me know if you are able to resolve it.

**Comment by GiuseppeCofano** [comment]
Thanks for the quick reply, it was a permission issue, I solved by adding the Project Editor role to the default service account (I guess the AI Platform Admin role is not enough!)

Btw I've created a pull request to add the logger from the Cloud Function sample, as you suggested.

**Comment by rominirani** [comment]
Thank you for highlighting that it was a permission issue. Thanks for the PR too -- it has been merged.

**Comment by AuroraLi** [comment]
I experienced the permission issue as well and got it fixed by using the latest python library. Could you please fix this because the old endpoint is deprecated?
